name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build Debug
        run: cargo build

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Build Debug
        run: cargo build --release

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Test
        run: cargo test