name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build release binary
        run: cargo build --release

      - name: Rename binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv target/release/cryptic target/release/cryptic-linux-${{ matrix.arch }}

      - name: Rename binary (MacOS)
        if: matrix.os == 'macos-latest'
        run: mv target/release/cryptic target/release/cryptic-mac-os-${{ matrix.arch }}

      - name: Rename binary (Windows)
        if: matrix.os == 'windows-latest'
        run: ren target\release\cryptic.exe cryptic-win-${{ matrix.arch }}.exe

      - name: Release (Linux)
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.GH_TOKEN }}
          body: "stub"
          files: target/release/cryptic-linux-${{ matrix.arch }}

      - name: Release (MacOS)
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'macos-latest'
        with:
          token: ${{ secrets.GH_TOKEN }}
          body: "stub"
          files: target/release/cryptic-mac-os-${{ matrix.arch }}

      - name: Release (Windows)
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'windows-latest'
        with:
          token: ${{ secrets.GH_TOKEN }}
          body: "stub"
          files: target/release/cryptic-win-${{ matrix.arch }}.exe